CREATE TABLE IF NOT EXISTS teams (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  country TEXT NOT NULL,
  group_name TEXT NOT NULL,
  crest_url TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS venues (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  country TEXT NOT NULL,
  capacity INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS players (
  id INTEGER PRIMARY KEY,
  team_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  position TEXT NOT NULL DEFAULT '',
  number INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS matches (
  id INTEGER PRIMARY KEY,
  stage TEXT NOT NULL,
  group_name TEXT NOT NULL DEFAULT '',
  venue_id INTEGER NOT NULL DEFAULT 0,
  home_id INTEGER NOT NULL DEFAULT 0,
  away_id INTEGER NOT NULL DEFAULT 0,
  kickoff_utc TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'scheduled',
  minute INTEGER NOT NULL DEFAULT 0,
  home_score INTEGER NOT NULL DEFAULT 0,
  away_score INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS match_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  match_id INTEGER NOT NULL,
  minute INTEGER NOT NULL,
  type TEXT NOT NULL,
  team_id INTEGER NOT NULL DEFAULT 0,
  player_id INTEGER NOT NULL DEFAULT 0,
  detail TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS standings (
  group_name TEXT NOT NULL,
  team_id INTEGER NOT NULL,
  played INTEGER NOT NULL DEFAULT 0,
  won INTEGER NOT NULL DEFAULT 0,
  drawn INTEGER NOT NULL DEFAULT 0,
  lost INTEGER NOT NULL DEFAULT 0,
  gf INTEGER NOT NULL DEFAULT 0,
  ga INTEGER NOT NULL DEFAULT 0,
  pts INTEGER NOT NULL DEFAULT 0,
  form TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (group_name, team_id)
);

CREATE TABLE IF NOT EXISTS follows (
  team_id INTEGER PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS reminders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  match_id INTEGER NOT NULL,
  lead_minutes INTEGER NOT NULL DEFAULT 30,
  fired INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS notes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  subject_type TEXT NOT NULL,
  subject_id INTEGER NOT NULL,
  body TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS prefs (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS meta_cache (
  resource TEXT PRIMARY KEY,
  fetched_at TEXT NOT NULL,
  ttl_seconds INTEGER NOT NULL DEFAULT 0
);
